// Home
export const CHANGE_SEARCH_INE = 'CHANGE_SEARCH_INE';
export const SET_LOADING_STATUS = 'SET_LOADING_STATUS';
export const SET_DISABLE_STATUS = 'SET_DISABLE_STATUS';
export const SET_ERROR_STATUS = 'SET_ERROR_STATUS';
export const SET_SUCCESS_STATUS = 'SET_SUCCESS_STATUS';
export const SET_MESSAGE_STATUS = 'SET_MESSAGE_STATUS';
